name: Fork Sync

on:
  schedule:
    # Runs at the top of every hour
    - cron: '0 * * * *'

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Fork Sync
        uses: tgymnich/fork-sync@v1.2.1
        with:
          owner: YOUR_GITHUB_USERNAME # Replace with your GitHub username or organization
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow
          head: master # Default is master, change if you use a different branch
          base: master # Default is master, change if you use a different branch
          merge_method: merge # Default is merge, can be changed to rebase or squash
          pr_title: Fork Sync # Default is Fork Sync, change if you want a different title
          pr_message: Update fork with latest changes # Replace with your desired PR message
          ignore_fail: false # Set to true if you want to ignore failures
